<?xml version='1.0' encoding='euc-kr' ?>

<!DOCTYPE helpset
  PUBLIC "-//Sun Microsystems Inc.//DTD JavaHelp HelpSet Version 1.0//EN"
         "http://java.sun.com/products/javahelp/helpset_1_0.dtd">


<helpset version="1.0">
  
<!-- title -->
  
<title>CPU스케줄링 도움말
</title>

 
 <!-- maps -->
  
<maps>
     
<homeID>top
</homeID>
     
<mapref location="Map.jhm"/>
  
</maps>

  
<!-- views -->
  
<view>

<name>TOC
</name>
       
<label>Table Of Contents</label>
    
<type>javax.help.TOCView</type>
    
<data>HelpTOC.xml</data>
  
</view>

<!--
  <view>
    
<name>Index</name>
    
<label>Index</label>
    
<type>javax.help.IndexView</type>
   
 <data>IdeHelpIndex.xml</data>
  
</view>

  <view>
   
 <name>Search</name>
    
<label>Search</label>
    
<type>javax.help.SearchView</type>
    <
data engine="com.sun.java.help.search.DefaultSearchEngine">
      JavaHelpSearch
    </data>
  </view>
-->

</helpset>
